CREATE TABLE IF NOT EXISTS product_types (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text UNIQUE NOT NULL,
  body_area text NOT NULL DEFAULT 'Face',
  created_at timestamptz DEFAULT now()
);

INSERT INTO product_types (name, body_area) VALUES
  ('Concentrate', 'Face'),
  ('Exfoliant', 'Face'),
  ('Eye Cream', 'Face'),
  ('Eye Primer', 'Face'),
  ('Face Mask', 'Face'),
  ('Face Wash', 'Face'),
  ('Makeup Remover', 'Face'),
  ('Mist', 'Face'),
  ('Moisturizer', 'Face'),
  ('Oil', 'Face'),
  ('Ointment', 'Face'),
  ('Primer', 'Face'),
  ('Serum', 'Face'),
  ('Sleeping Mask', 'Face'),
  ('Spot Patches', 'Face'),
  ('Sun Screen', 'Face'),
  ('Toner', 'Face'),
  ('BB Cream', 'Makeup'),
  ('Blush', 'Makeup'),
  ('Brow Gel', 'Makeup'),
  ('CC Cream', 'Makeup'),
  ('Concealer', 'Makeup'),
  ('Eyeliner', 'Makeup'),
  ('Eyeshadow', 'Makeup'),
  ('Foundation', 'Makeup'),
  ('Mascara', 'Makeup'),
  ('Setting Spray', 'Makeup'),
  ('Lip Balm', 'Lips'),
  ('Lip Treatment', 'Lips'),
  ('Body Lotion', 'Body'),
  ('Body Wash', 'Body'),
  ('Deodorant', 'Body'),
  ('Foot Cream', 'Body'),
  ('Hand Cream', 'Body'),
  ('Conditioner', 'Hair'),
  ('Hair Treatment', 'Hair'),
  ('Scalp Treatment', 'Hair'),
  ('Shampoo', 'Hair')
ON CONFLICT (name) DO NOTHING;
